esphome:
  name: airsensor
  friendly_name: "Air Quality Monitor"

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret airsensor_encryption_key

ota:
  - platform: esphome
    password: !secret airsensor_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Airsensor Fallback Hotspot"
    password: !secret airsensor_ap_password

captive_portal:

# External component for M702UART sensor
external_components:
  - source: github://julianpas/esphome-m702uart@main
    components: [ m702uart ]
    refresh: 1min

# UART configuration for M702UART sensor
uart:
  # tx_pin: GPIO5  # D10 (TX)
  rx_pin: GPIO4  # D9 (RX)
  baud_rate: 9600
  id: uart_m702uart

# M702UART Air Quality Sensor
m702uart:
  uart_id: uart_m702uart
  update_interval: 30s
  eco2:
    name: "eCO2"
    unit_of_measurement: "ppm"
    device_class: "carbon_dioxide"
    state_class: "measurement"
    icon: "mdi:molecule-co2"
  ozone:
    name: "Ozone"
    unit_of_measurement: "ppb"
    device_class: "ozone"
    state_class: "measurement"
    icon: "mdi:chemical-weapon"
  tvoc:
    name: "TVOC"
    unit_of_measurement: "ppb"
    device_class: "volatile_organic_compounds"
    state_class: "measurement"
    icon: "mdi:air-filter"
  pm_2_5:
    name: "PM2.5"
    unit_of_measurement: "µg/m³"
    device_class: "pm25"
    state_class: "measurement"
    icon: "mdi:blur"
  pm_10:
    name: "PM10"
    unit_of_measurement: "µg/m³"
    device_class: "pm10"
    state_class: "measurement"
    icon: "mdi:blur"
  temperature:
    name: "Temperature"
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 2
  humidity:
    name: "Humidity"
    unit_of_measurement: "%"
    device_class: "humidity"
    state_class: "measurement"
    accuracy_decimals: 2
  data_valid:
    name: "Sensor Data Valid"
    device_class: "connectivity"
  sensor_status:
    name: "Sensor Status"
    icon: "mdi:information"

# Switch to restart the device
switch:
  - platform: restart
    name: "Restart Device"
